#-------------------------------------------------------------------------------
#			ADJUSTABLE PARAMETERS                                   
#-------------------------------------------------------------------------------


amber			on
parmfile		./C3b_leap.parm7
ambercoor		./C3b_leap.rst7
outputName		./output/1-min   



set temperature		0

firsttimestep		0



#-------------------------------------------------------------------------------
#			SIMULATION PARAMETERS
#-------------------------------------------------------------------------------

#----- Input

temperature		$temperature
 

#----- Periodic Boundary conditions

set dist 164.3664

set xx [expr $dist]
set xy [expr $dist * 1/3]
set xz [expr $dist * -1/3]

set yx [expr 0]
set yy [expr $dist * sqrt(2) * 2/3]
set yz [expr $dist * sqrt(2) * 1/3]

set zx [expr 0]
set zy [expr 0]
set zz [expr $dist * sqrt(6) * 1/3]

cellBasisVector1    $xx $yx $zx
cellBasisVector2    $xy $yy $zy
cellBasisVector3    $xz $yz $zz
cellOrigin  89.45719909667969 89.32687377929688 89.41411590576172

#----- Water Parameters
 
wrapWater		on
wrapAll			on
watermodel              tip4

#----- Force-Field Parameters
exclude			scaled1-4
1-4scaling          	0.833333
cutoff              	12.0
switching           	on
switchdist          	10.0
pairlistdist       	13.5
scnb                    2.0
readexclusions          no
#LJcorrection            off
#ZeroMomentum            off

#----- Integrator Parameters

timestep		1.0  # 2fs/step
rigidBonds		all  # needed for 2fs steps
rigidTolerance		0.00001 # for Amber, 0.00000001 for Charmm   
nonbondedFreq		1
fullElectFrequency	1 
stepspercycle		10

#----- PME (for full-system periodic electrostatics)

PME			yes
PMEGridSpacing		1.0


#--------------------  Constant T/P contrl, useless here  ---------------------


#------ Constant Temperature Control
langevin		on    # do langevin dynamics
langevinDamping		1
langevinTemp		$temperature
langevinHydrogen	no    # don't couple langevin bath to hydrogens

#----- Constant Pressure Control (variable volume)

#useGroupPressure	yes # needed for 2fs steps
#useFlexibleCell		no  # no for water box, yes for membrane
#useConstantArea		no  # no for water box, yes for membrane
#
#langevinPiston		on
#langevinPistonTarget	1.01325 #  in bar -> 1 atm
##langevinPistonPeriod	100.0
##langevinPistonDecay	50.0
#langevinPistonPeriod	200.0
#langevinPistonDecay	100.0
#langevinPistonTemp	$temperature
#------------------------------------------------------------------------------


#----- How often to write into files; smaller value = more frequent = larger
#----- file size

restartfreq		1000     # 500steps = every 1ps
dcdfreq			1000
xstFreq			1000
outputEnergies		1000
outputPressure		1000

#----- Constrained Atoms Constraint (set PDB beta-column to 1)

constraints        on
consref            ./reference.pdb
conskfile          ./reference.pdb
conskcol           B
#constraintScaling  500.0

#margin 3.0


#------------------------------------------------------------------------------
#				EXTRA PARAMETERS
#------------------------------------------------------------------------------


#	Put here any custom parameters that are specific to 
#	this job (e.g., SMD, TclForces, etc...)



#------------------------------------------------------------------------------
#				EXECUTION SCRIPT
#------------------------------------------------------------------------------


#------ Minimization

minimization    on

set factor 10
set nall 10
set n 1
while {$n <= $nall} {
    constraintScaling $factor
    minimize 1000
    set n [expr $n + 1]
    set factor [expr $factor * 0.5]
}
constraintScaling 0
minimize 1000


