#############################################################
## Step 1   约束backbone、Mg离子,优化水                    ##
#############################################################

#		this simulation do a 3 steps minimization		      #
#		step1 fix all non-water,minimize water			      #


#------------------------------------------------------------------------------
#			ADJUSTABLE PARAMETERS
#------------------------------------------------------------------------------


amber			on
parmfile		./C3b_leap.parm7
ambercoor		./C3b_leap.rst7
outputName		./output/2-heat

set inputname           1-min
binCoordinates          ./output/$inputname.restart.coor
binVelocities           ./output/$inputname.restart.vel 
extendedSystem          ./output/$inputname.restart.xsc

set temperature		60

firsttimestep		0

#------------------------------------------------------------------------------
#			SIMULATION PARAMETERS                                  
#------------------------------------------------------------------------------

#----- Water Parameters

wrapWater               on
wrapAll                 on
watermodel              tip4

#----- Force-Field Parameters

exclude                 scaled1-4
1-4scaling              0.833333
cutoff                  12.0
switching               on
switchdist              10.0
pairlistdist            13.5
scnb                    2.0
readexclusions          no
#LJcorrection            off
#ZeroMomentum            off

#----- Integrator Parameters

timestep		2.0  # 2fs/step
rigidBonds		all  # needed for 2fs steps
rigidTolerance		0.00001 # for Amber  0.00000001 for Charmm   
nonbondedFreq		1
fullElectFrequency	2  
stepspercycle		20

#----- PME (for full-system periodic electrostatics)

PME			yes
PMEGridSpacing		1.0

#------------------- Constant T/P contrl, useless here ------------------------


#----- Constant Temperature Control

langevin		on    # do langevin dynamics
langevinDamping		1
langevinTemp		$temperature
langevinHydrogen	no    # don't couple langevin bath to hydrogens

#----- Constant Pressure Control (variable volume)

useGroupPressure	yes # needed for 2fs steps
useFlexibleCell		no  # no for water box, yes for membrane
useConstantArea		no  # no for water box, yes for membrane

#if {0} {
#langevinPiston		on
#langevinPistonTarget	1.01325 #  in bar -> 1 atm
##langevinPistonPeriod	100.0
##langevinPistonDecay	50.0
#langevinPistonPeriod	200.0
#langevinPistonDecay	100.0
#langevinPistonTemp	$temperature
#}

#------------------------------------------------------------------------------


#----- Frequency of data writing; lesser value = more frequent = larger file

restartfreq		1000     # 500steps = every 1ps
dcdfreq			1000
xstFreq			1000
outputEnergies		1000
outputPressure		1000

#----- Fixed Atoms Constraint (set PDB beta-column to 1)

#fixedAtoms		no
#fixedAtomsForces	off
#fixedAtomsFile		./prep/4j5t_wat.pdb
#fixedAtomsCol		B

#----- (lipid and name P) or backbone or (segname B12 and noh)

constraints        on
consref            ./reference.pdb
conskfile          ./reference.pdb
conskcol           B
#constraintScaling  10.0
#margin 1.0

#------------------------------------------------------------------------------
#			EXTRA PARAMETERS
#------------------------------------------------------------------------------

#	Put here any custom parameters that are specific to 
#	this job (e.g., SMD, TclForces, etc...)


#------------------------------------------------------------------------------
#			EXECUTION SCRIPT
#------------------------------------------------------------------------------

# Heating

constraintScaling 1
reinitvels      $temperature
for {set T $temperature} {$T < 310} {incr T 10} {
    langevinTemp       $T;
    run              2000;
}
langevinTemp     310
run             10000

